en:
  languageName: "ğŸ‡¬ğŸ‡§ English"
  languageCode: en
  weight: 1
  title: "Bait Gameel | Unlock Egypt: Stunning Stays, Memorable Journeys"

ar:
  disabled: false
  languageName: "ğŸ‡ªğŸ‡¬ Ø§Ù„Ø¹Ø±Ø¨ÙŠØ©"
  languageCode: ar
  weight: 2
  title: "Ø¨ÙŠØª Ø¬Ù…ÙŠÙ„ | Ù…ØµØ± Ø¨Ø±Ø¤ÙŠØ© Ø¬Ø¯ÙŠØ¯Ø©: Ø¥Ù‚Ø§Ù…Ø© ÙØ§Ø®Ø±Ø© ÙˆØªØ¬Ø§Ø±Ø¨ Ù„Ø§ ØªÙ†Ø³Ù‰"
  languageDirection: rtl
